### ISSUE TITLE
Create e-mail and mailing list

### ISSUE THREAD

**Issue by JakobMiksch** [augustinh22/AGI-skillshare#3]

**Comment by augustinh22** [comment]
I added a request for a maptime.io e-mail to the maptime issue to take care of our chapter. In the meantime, we can be contacted at: maptime.sbg[ÄT]gmail[DOT]com

We can use google groups to create what are essentially mailing lists at the moment -- as things get bigger we can look at other solutions that allow users to subscribe and unsubscribe on their own....

**Comment by augustinh22** [comment]
open-source mailing list options: https://www.bettertechtips.com/linux/mailchimp-alternatives-open-source/

**Comment by JakobMiksch** [comment]
Protonmail cannot be added to Thunderbird, therefore I would choose Gmail for the beginning. We can still change it later ...

**Comment by augustinh22** [comment]
This can be re-opened if the Gmail mailing group starts to be unmanageable (e.g. manually adding and removing subscribers). Just be sure to send all messages using the group as BCC, so as not to share all of the e-mails!
